[tox]
skip_missing_interpreters=true
envlist = {py27,py34}-{linux}

[testenv]
deps=
	docopt
	colorama
	docker
#commands=python scripts/test.py
#commands=ctinfo

[flake8]
# E126 continuation line over-indented for hanging indent
# E128 continuation line under-indented for visual indent
# H305 imports not grouped correctly
#ignore = E126, E128, H305, E402
max-line-length = 100
